name: MyCraftSpawner
main: com.toyz.mcs.mcs
version: 1.2
author: Toyz
description: Turns all spawners into a craftable item
commands:
  mcs:
    description: Base MCS command
permissions:
  #admin commands permissions
  mcs.admin.reload:
    description: Reload the plugin
    default: op